// Autogenerated. DO NOT EDIT.

package fakebackend

func init() {
	xhsDb = dbXHs{
		xhKey{"default", 10, 72}: 5.46875,
		xhKey{"default", 12, 72}: 6.5625,
		xhKey{"regular", 10, 72}: 5.46875,
		xhKey{"regular", 12, 72}: 6.5625,
		xhKey{"rm", 10, 72}:      5.46875,
		xhKey{"rm", 12, 72}:      6.5625,
		xhKey{"it", 10, 72}:      5.46875,
		xhKey{"it", 12, 72}:      6.5625,
	}
}
